---
- name: Extract join command
  command: "sudo microk8s.add-node"
  register: join_command

- name: Save join command
  local_action: copy content={{ join_command.stdout_lines | last  | trim }} dest="{{ join_command_location }}"

- name: Copy join command to worker nodes
  local_action: ansible.builtin.command rsync -a {{join_command_location}} {{ item }}:{{ join_command_location }}

- name: Read join command on worker nodes
  debug: msg="{{ lookup('file', join_command_location) }}"
  register: join_command_local

- name: Join Workers to cluster
  command: "{{ join_command_local.msg }}"
  delegate_to: "{{ item }}"
  ignore_errors: True
