#!/bin/bash
# Configure WireGuard VPN client on local machine
#
# This script sets up WireGuard client from exported server configuration
#
# Usage:
#   ./configure_wireguard_client.sh <config-file> [interface-name]
#   ./configure_wireguard_client.sh client.conf
#   ./configure_wireguard_client.sh client.conf myvpn
#

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
CONFIG_FILE="${1:-}"
INTERFACE_NAME="${2:-wg0}"
WIREGUARD_DIR="/etc/wireguard"

# Functions
print_header() {
    echo -e "${BLUE}====== $1 ======${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

show_usage() {
    cat << EOF
Usage: $0 <config-file> [interface-name]

Arguments:
  config-file      Path to WireGuard configuration file (required)
  interface-name   WireGuard interface name (default: wg0)

Examples:
  $0 client.conf
  $0 /tmp/laptop.conf myvpn
  $0 ~/wireguard/office.conf office-vpn

Configuration files can be obtained by:
  1. From WireGuard server admin
  2. Using QR code scan
  3. Generated by server's wg-gen-client script

Note: Requires root privileges to install

EOF
}

check_requirements() {
    print_header "Checking Requirements"

    # Check if running as root
    if [ "$EUID" -ne 0 ]; then
        print_error "This script requires root privileges"
        echo "Run with: sudo $0 $@"
        exit 1
    fi

    print_success "Running with root privileges"

    # Check if WireGuard is installed
    if ! command -v wg &> /dev/null; then
        print_warning "WireGuard not installed, installing..."

        if command -v apt-get &> /dev/null; then
            apt-get update
            apt-get install -y wireguard wireguard-tools
        elif command -v yum &> /dev/null; then
            yum install -y wireguard-tools
        elif command -v brew &> /dev/null; then
            brew install wireguard-tools
        else
            print_error "Could not install WireGuard. Please install manually."
            exit 1
        fi
    fi

    print_success "WireGuard is installed"

    # Check if config file exists
    if [ ! -f "$CONFIG_FILE" ]; then
        print_error "Configuration file not found: $CONFIG_FILE"
        exit 1
    fi

    print_success "Configuration file found: $CONFIG_FILE"
}

validate_config() {
    print_header "Validating Configuration"

    # Check for required sections
    if ! grep -q "^\[Interface\]" "$CONFIG_FILE"; then
        print_error "[Interface] section not found in config"
        exit 1
    fi

    print_success "[Interface] section found"

    if ! grep -q "^\[Peer\]" "$CONFIG_FILE"; then
        print_error "[Peer] section not found in config"
        exit 1
    fi

    print_success "[Peer] section found"

    # Check for required keys
    if ! grep -q "PrivateKey" "$CONFIG_FILE"; then
        print_error "PrivateKey not found in config"
        exit 1
    fi

    print_success "PrivateKey found"

    if ! grep -q "PublicKey" "$CONFIG_FILE"; then
        print_error "PublicKey not found in config"
        exit 1
    fi

    print_success "PublicKey found"
}

install_config() {
    print_header "Installing Configuration"

    # Create WireGuard directory if needed
    if [ ! -d "$WIREGUARD_DIR" ]; then
        mkdir -p "$WIREGUARD_DIR"
        chmod 700 "$WIREGUARD_DIR"
        print_success "Created $WIREGUARD_DIR"
    fi

    # Copy configuration
    DEST_FILE="$WIREGUARD_DIR/${INTERFACE_NAME}.conf"

    # Backup existing config if present
    if [ -f "$DEST_FILE" ]; then
        BACKUP_FILE="${DEST_FILE}.backup.$(date +%Y%m%d-%H%M%S)"
        cp "$DEST_FILE" "$BACKUP_FILE"
        print_warning "Existing configuration backed up to: $BACKUP_FILE"
    fi

    # Copy and set permissions
    cp "$CONFIG_FILE" "$DEST_FILE"
    chmod 600 "$DEST_FILE"

    print_success "Configuration installed to: $DEST_FILE"
}

enable_service() {
    print_header "Enabling WireGuard Service"

    # Check if systemd is available
    if command -v systemctl &> /dev/null; then
        # Enable service
        systemctl enable "wg-quick@${INTERFACE_NAME}"
        print_success "WireGuard service enabled"

        # Start service
        systemctl start "wg-quick@${INTERFACE_NAME}"
        print_success "WireGuard service started"
    else
        print_warning "systemd not available, skipping service installation"
        print_warning "Start manually with: wg-quick up $INTERFACE_NAME"
    fi
}

verify_connection() {
    print_header "Verifying Connection"

    # Wait for interface to be up
    sleep 2

    # Check if interface exists
    if ip link show "$INTERFACE_NAME" &> /dev/null; then
        print_success "Interface $INTERFACE_NAME is up"
    else
        print_error "Interface $INTERFACE_NAME is not up"
        return 1
    fi

    # Get VPN IP
    VPN_IP=$(ip addr show "$INTERFACE_NAME" 2>/dev/null | grep "inet " | awk '{print $2}' | cut -d'/' -f1)

    if [ -n "$VPN_IP" ]; then
        print_success "VPN IP assigned: $VPN_IP"
    else
        print_warning "Could not determine VPN IP"
    fi

    # Show WireGuard status
    echo ""
    echo "WireGuard Interface Status:"
    wg show "$INTERFACE_NAME" 2>/dev/null || true

    echo ""
    echo "Network Interface Status:"
    ip addr show "$INTERFACE_NAME" 2>/dev/null || true

    return 0
}

show_management_commands() {
    print_header "Management Commands"

    cat << EOF

Service Management:
  Check status:    sudo systemctl status wg-quick@${INTERFACE_NAME}
  Start:           sudo systemctl start wg-quick@${INTERFACE_NAME}
  Stop:            sudo systemctl stop wg-quick@${INTERFACE_NAME}
  Restart:         sudo systemctl restart wg-quick@${INTERFACE_NAME}
  View logs:       sudo journalctl -u wg-quick@${INTERFACE_NAME} -f

WireGuard Interface:
  Manual start:    sudo wg-quick up ${INTERFACE_NAME}
  Manual stop:     sudo wg-quick down ${INTERFACE_NAME}
  Show status:     sudo wg show ${INTERFACE_NAME}
  Show interface:  ip addr show ${INTERFACE_NAME}

Connectivity Tests:
  Ping VPN IP:     ping <gateway-ip>
  Traceroute:      traceroute <remote-ip>
  DNS test:        nslookup cluster.local
  Speed test:      iperf3 -c <server-ip>

Configuration:
  View config:     cat $DEST_FILE
  Edit config:     sudo nano $DEST_FILE
  Edit address:    Edit Address= line in config and restart
  Change DNS:      Edit DNS= line in config and restart

Troubleshooting:
  Check port:      ss -tulpn | grep :51820
  Check firewall:  sudo ufw status
  Check routing:   ip route show
  Debug logs:      journalctl -u wg-quick@${INTERFACE_NAME} -n 50

EOF
}

main() {
    # Check arguments
    if [ -z "$CONFIG_FILE" ]; then
        print_error "Configuration file not specified"
        echo ""
        show_usage
        exit 1
    fi

    # Run checks
    print_header "WireGuard Client Configuration"
    echo "Configuration File: $CONFIG_FILE"
    echo "Interface Name: $INTERFACE_NAME"
    echo ""

    check_requirements
    echo ""

    validate_config
    echo ""

    install_config
    echo ""

    enable_service
    echo ""

    if verify_connection; then
        echo ""
        print_success "WireGuard client successfully configured!"
        echo ""
        show_management_commands
    else
        print_warning "Could not verify connection, check configuration"
        show_management_commands
        exit 1
    fi
}

# Run main function
main
